function W = Wel(rhoe,L)
%% Function for setting the shape funtions to be used for displacement field calculations
    W= @(x)shape(x,L,1)*rhoe(1) ...
           +shape(x,L,2)*rhoe(2) ...
           +shape(x,L,3)*rhoe(3) ...
           +shape(x,L,4)*rhoe(4);
end